### ISSUE TITLE
preg_replace() can give-up on long strings and this results in empty translated page

### ISSUE THREAD

**Issue by GeorgeBotsev** [OnTheGoSystems/wpml-page-builders#6] opened 2018-03-01 10:54 UTC
If we have a very long string that we need to process, then preg_replace can fail and return NULL.
This results in the fact that the contents of the translation are blank in the resultant translated page/post.
Here is the error log:
`[01-Mar-2018 10:44:50 UTC] PHP Warning:  preg_replace(): Compilation failed: regular expression is too large at offset 69790 in /var/www/cats.com/wp-content/plugins/sitepress-multilingual-cms/vendor/wpml/page-builders/src/st/strategy/shortcode/class-wpml-pb-update-shortcodes-in-content.php on line 91
[01-Mar-2018 10:44:50 UTC] PHP Stack trace:
[01-Mar-2018 10:44:50 UTC] PHP   1. {main}() /var/www/cats.com/wp-admin/admin-ajax.php:0
[01-Mar-2018 10:44:50 UTC] PHP   2. do_action() /var/www/cats.com/wp-admin/admin-ajax.php:97
[01-Mar-2018 10:44:50 UTC] PHP   3. WP_Hook->do_action() /var/www/cats.com/wp-includes/plugin.php:453
[01-Mar-2018 10:44:50 UTC] PHP   4. WP_Hook->apply_filters() /var/www/cats.com/wp-includes/class-wp-hook.php:310
[01-Mar-2018 10:44:50 UTC] PHP   5. call_user_func_array:{/var/www/cats.com/wp-includes/class-wp-hook.php:286}() /var/www/cats.com/wp-includes/class-wp-hook.php:286
[01-Mar-2018 10:44:50 UTC] PHP   6. wpml_save_job_ajax() /var/www/cats.com/wp-includes/class-wp-hook.php:286
[01-Mar-2018 10:44:50 UTC] PHP   7. WPML_TM_Editor_Job_Save->save() /var/www/cats.com/wp-content/plugins/wpml-translation-management/inc/ajax.php:46
[01-Mar-2018 10:44:50 UTC] PHP   8. WPML_TM_Editor_Save_Ajax_Action->run() /var/www/cats.com/wp-content/plugins/wpml-translation-management/classes/menu/translation-editor/class-wpml-tm-editor-job-save.php:12
[01-Mar-2018 10:44:50 UTC] PHP   9. WPML_Save_Translation_Data_Action->save_translation() /var/www/cats.com/wp-content/plugins/wpml-translation-management/classes/menu/translation-editor/class-wpml-tm-editor-save-ajax-action.php:21
[01-Mar-2018 10:44:50 UTC] PHP  10. do_action() /var/www/cats.com/wp-content/plugins/wpml-translation-management/inc/translation-jobs/helpers/wpml-save-translation-data-action.class.php:287
[01-Mar-2018 10:44:50 UTC] PHP  11. WP_Hook->do_action() /var/www/cats.com/wp-includes/plugin.php:453
[01-Mar-2018 10:44:50 UTC] PHP  12. WP_Hook->apply_filters() /var/www/cats.com/wp-includes/class-wp-hook.php:310
[01-Mar-2018 10:44:50 UTC] PHP  13. call_user_func_array:{/var/www/cats.com/wp-includes/class-wp-hook.php:286}() /var/www/cats.com/wp-includes/class-wp-hook.php:286
[01-Mar-2018 10:44:50 UTC] PHP  14. WPML_TM_Page_Builders_Hooks->pro_translation_completed_action() /var/www/cats.com/wp-includes/class-wp-hook.php:286
[01-Mar-2018 10:44:50 UTC] PHP  15. WPML_TM_Page_Builders->pro_translation_completed_action() /var/www/cats.com/wp-content/plugins/sitepress-multilingual-cms/vendor/wpml/page-builders/src/tm/class-wpml-tm-page-builders-hooks.php:48
[01-Mar-2018 10:44:50 UTC] PHP  16. do_action() /var/www/cats.com/wp-content/plugins/sitepress-multilingual-cms/vendor/wpml/page-builders/src/tm/class-wpml-tm-page-builders.php:100
[01-Mar-2018 10:44:50 UTC] PHP  17. WP_Hook->do_action() /var/www/cats.com/wp-includes/plugin.php:453
[01-Mar-2018 10:44:50 UTC] PHP  18. WP_Hook->apply_filters() /var/www/cats.com/wp-includes/class-wp-hook.php:310
[01-Mar-2018 10:44:50 UTC] PHP  19. call_user_func_array:{/var/www/cats.com/wp-includes/class-wp-hook.php:286}() /var/www/cats.com/wp-includes/class-wp-hook.php:286
[01-Mar-2018 10:44:50 UTC] PHP  20. WPML_Package_Helper->add_string_translation_action() /var/www/cats.com/wp-includes/class-wp-hook.php:286
[01-Mar-2018 10:44:50 UTC] PHP  21. icl_add_string_translation() /var/www/cats.com/wp-content/plugins/wpml-string-translation/inc/package-translation/inc/wpml-package-translation-helper.class.php:665
[01-Mar-2018 10:44:50 UTC] PHP  22. WPML_ST_String->set_translation() /var/www/cats.com/wp-content/plugins/wpml-string-translation/inc/functions.php:478
[01-Mar-2018 10:44:50 UTC] PHP  23. do_action() /var/www/cats.com/wp-content/plugins/wpml-string-translation/classes/class-wpml-st-string.php:232
[01-Mar-2018 10:44:50 UTC] PHP  24. WP_Hook->do_action() /var/www/cats.com/wp-includes/plugin.php:453
[01-Mar-2018 10:44:50 UTC] PHP  25. WP_Hook->apply_filters() /var/www/cats.com/wp-includes/class-wp-hook.php:310
[01-Mar-2018 10:44:50 UTC] PHP  26. call_user_func_array:{/var/www/cats.com/wp-includes/class-wp-hook.php:286}() /var/www/cats.com/wp-includes/class-wp-hook.php:286
[01-Mar-2018 10:44:50 UTC] PHP  27. WPML_PB_Integration->new_translation() /var/www/cats.com/wp-includes/class-wp-hook.php:286
[01-Mar-2018 10:44:50 UTC] PHP  28. WPML_PB_String_Translation->new_translation() /var/www/cats.com/wp-content/plugins/sitepress-multilingual-cms/vendor/wpml/page-builders/src/st/class-wpml-pb-integration.php:132
[01-Mar-2018 10:44:50 UTC] PHP  29. WPML_PB_String_Translation->save_translations_to_post() /var/www/cats.com/wp-content/plugins/sitepress-multilingual-cms/vendor/wpml/page-builders/src/st/class-wpml-pb-string-translation.php:31
[01-Mar-2018 10:44:50 UTC] PHP  30. WPML_PB_Update_Post->update() /var/www/cats.com/wp-content/plugins/sitepress-multilingual-cms/vendor/wpml/page-builders/src/st/class-wpml-pb-string-translation.php:41
[01-Mar-2018 10:44:50 UTC] PHP  31. WPML_PB_Update_Post->update_post() /var/www/cats.com/wp-content/plugins/sitepress-multilingual-cms/vendor/wpml/page-builders/src/st/class-wpml-pb-update-post.php:35
[01-Mar-2018 10:44:50 UTC] PHP  32. WPML_PB_Update_Shortcodes_In_Content->update() /var/www/cats.com/wp-content/plugins/sitepress-multilingual-cms/vendor/wpml/page-builders/src/st/class-wpml-pb-update-post.php:42
[01-Mar-2018 10:44:50 UTC] PHP  33. WPML_PB_Update_Shortcodes_In_Content->update_content() /var/www/cats.com/wp-content/plugins/sitepress-multilingual-cms/vendor/wpml/page-builders/src/st/strategy/shortcode/class-wpml-pb-update-shortcodes-in-content.php:23
[01-Mar-2018 10:44:50 UTC] PHP  34. WPML_PB_Update_Shortcodes_In_Content->update_shortcodes() /var/www/cats.com/wp-content/plugins/sitepress-multilingual-cms/vendor/wpml/page-builders/src/st/strategy/shortcode/class-wpml-pb-update-shortcodes-in-content.php:50
[01-Mar-2018 10:44:50 UTC] PHP  35. WPML_PB_Update_Shortcodes_In_Content->replace_string_with_translation() /var/www/cats.com/wp-content/plugins/sitepress-multilingual-cms/vendor/wpml/page-builders/src/st/strategy/shortcode/class-wpml-pb-update-shortcodes-in-content.php:60
[01-Mar-2018 10:44:51 UTC] PHP  36. preg_replace() /var/www/cats.com/wp-content/plugins/sitepress-multilingual-cms/vendor/wpml/page-builders/src/st/strategy/shortcode/class-wpml-pb-update-shortcodes-in-content.php:91`

As you can see the error comes from: preg_replace() being called in sitepress-multilingual-cms/vendor/wpml/page-builders/src/st/strategy/shortcode/class-wpml-pb-update-shortcodes-in-content.php on line 88, 91 and 93

I tested with increasing the limit by doing: 
`ini_set('pcre.backtrack_limit', 9999999999);`
but this had no result in my setup

**Comment by andreasciamanna** [comment] 2018-03-02 08:47
There are [ways to optimize a regular expression](https://stackoverflow.com/a/31176468/626538). However, none of them applies to our case because the problem is the original string which we can't control.

It may require some investigation and probably I'm not considering some edge cases where this can't be applied.
We could replace all `[` with `<` and `]` with `>` and then handle the string as an XML.
Using [DOMDocument](http://php.net/domdocument), the DOM tree can be traversed with the available API or by using XPath to find specific elements.
With the same API, we can find and replace specific string such as attributes and text in nodes.
Once we adjust all this data, we can replace all `<` and `>` with `[` and `]` respectively.

Anyway, I don't know the library enough to be sure this approach is a suitable one.

@adrianosferreira @BruceOnTheGo if you have any thought or idea, please share it.

**Comment by adrianosferreira** [comment] 2018-03-02 12:41
@andreasciamanna @brucepearson I think we could split the string into smaller chunks and merge them in the end.

**Comment by adrianosferreira** [comment] 2018-03-02 13:51
Forget about my idea, it is impossible to break it into chunks because it will mess the translation. The problematic method already handles it per attribute, so we can't break more.

**Comment by adrianosferreira** [comment] 2018-03-03 19:15
@andreasciamanna @brucepearson I have been thinking about this problem a bit: right now we have two kinds of page builders handler, shortcode and custom fields.

For custom fields, we simply fetch the custom field data and convert it to an array, in order to properly manipulate it. Why don't we do the same with shortcodes?

I know it is kind of huge refactoring, not something we want to do now, but we could create kind of a shortcode parser for converting any shortcode into an array. I know we have some page builder, like Visual Composer, which does not hold IDs, which makes the manipulation a bit harder. But I think we could generate a random ID for each shortcode node when converting it to an array, so we have a way to connect the package to the array data.

Through this change, we will have one final page builder handler (like we have for Elementor / Beaver Builder / VC Website Builder) with many adaptor classes (one for shortcodes, one for each custom fields page builder).

For shortcode adaptor class:
- We will basically fetch the shortcode and parse it (already adding random ID when it is not found)
- We iterate over the whole array, knowing all translatable nodes (information coming from `wpml-config.xml`)
- Extract those nodes, create packages and display in the TE
- User translates
- We add it back to the array
- Apply some kind of reverse engineering to assemble it back to shortcodes format.

Maybe I'm forgetting about something but I think it is doable.

**Comment by andreasciamanna** [comment] 2018-03-08 16:52
> For custom fields, we simply fetch the custom field data and convert it to an array, in order to properly manipulate it. Why don't we do the same with shortcodes?

I don't know why we don't do it.
Also, I don't know how exactly we convert them into arrays: how do we tell the shortcode attributes from its content?

In any case, any solution which makes possible to manipulate the shortcode data without relying on complex regular expressions (which in this case are not an option anyway), is more than welcome.

If this requires a lot of work, we should discuss together if we must postpone 4.0.0 or this fix.

**Comment by adrianosferreira** [comment] 2018-03-12 20:08
@andreasciamanna as changing our current approach when handling shortcodes page builders will be a huge task, I've been thinking in another way to solve this problem for 4.0.0.

I read a lot about of Pre-Defined Subroutines in regex, good source here http://www.rexegg.com/regex-disambiguation.html#define

I think it may do the trick. I must say that I took quite some time to understand how it could help us, I mean, what is the difference between it and what we are already doing. So, I got it. If I am right, the memory issue happens because the matching pattern is too big, the long string is on it. Through the approach I am suggesting, the matching pattern will rather be a single `(?&text)`, which is our subroutine.

As this is something new to me, maybe you + @brucepearson can say whether we can use it or not. This is the PR I've just pushed: https://github.com/OnTheGoSystems/wpml-page-builders/pulls

**Comment by andreasciamanna** [comment] 2018-03-13 09:05
I had a look at that PR, and I don't understand what I'm seeing.

I thought we agreed years ago that code must be readable, but I also understand that my bias against regular expressions may lead me to not contribute to this discussion neutrally.

Therefore, let's continue the discussion when Bruce is back.

**Comment by adrianosferreira** [comment] 2018-03-13 11:31
@andreasciamanna I know we will discuss when Bruce is here, anyway let me just comment something. In my PR it was kind of minified, here is the expression in a readable manner:

```
/(?(DEFINE)                            
  (?<text>(]\s*)Some original string(\s*\[))
)                                     

##### The regex matching starts here #####
(?&text)/x
```

It is exactly the same expression but inside of a subroutine (it's nice because it is kind of procedural). You can check a live example: https://regex101.com/r/tD0yO1/85

**Comment by strategio** [comment] 2020-03-27 14:13
This bug was fixed with https://github.com/OnTheGoSystems/wpml-page-builders/pull/19, we can close the issue.

**Closed by strategio** 2020-03-27 14:13 UTC
Labels: bug
